### PR TITLE
Soot transformation error

### PR DESCRIPTION
**Pull request by hsanchez**
@martinschaef 

I have created this pull request so you can see my implementation (See SystemTest01 and DefaultEnvironment classes). Having said that, please don't merge this pull request. Thank you

### CODE REVIEW

**Comment by martinschaef** [comment]
Cool ... let me know when you beat my pre-commit hook ;)

**Comment by hsanchez** [comment]
@martinschaef Feel fee to review this PR.. Look at SystemTest03.java... I will handle the code coverage issue later...

**Comment by hsanchez** [comment]
@martinschaef Code coverage wins again :(. The requested implementation is there. It performs the use case you wanted. Feel free to play with it.

**Comment by martinschaef** [comment]
I tried to switch the coverage check off ... it was only supposed to run for pull requests to Master. No sure why it ran it on Devel as well.

**Pull request merged**
