### PR TITLE
Randoop

### PR DESCRIPTION
**Pull request by hsanchez**
@martinschaef , here is the Randoop stuff for you to review

### CODE REVIEW

**Comment by martinschaef** [comment]
There are a few compile errors in RegressionTest0 such as
/home/travis/build/jayhorn/jayhorn/jayhorn/src/test/java/jayhorn/test/randoop_tests/RegressionTest0.java:error: cannot find symbol boolean b5 = options0.hasScope();
Did you forget to add a file? Or did you add files that shouldn't be there?

**Comment by hsanchez** [comment]
hmm. let me check. this is an interesting error. Particularly, since it is
complaining about not finding jayhorn.Options class (which is in the
Jayhorn's classpath --- there are other tests in the RegressionTest0 that
use it):

```java
jayhorn.Options options0 = jayhorn.Options.v();
boolean b1 = options0.hasScope();
```
Are you in today?


Cheers,
Huascar A. Sanchez

**Comment by martinschaef** [comment]
Looks like classpath confusion. I won't be in today. Probably try to compile it on pascali or some other machine to reproduce the error.

**Comment by hsanchez** [comment]
@martinschaef  findbugs' checks failed. None of the classes that findbugs is complaining are classes covered by my changes. The affected classes are jayhorn's classes.

**Comment by martinschaef** [comment]
Interesting. I don't get them on my machine. Would you mind fixing them?

**Comment by hsanchez** [comment]
ok. I will fix them.

Cheers,
Huascar A. Sanchez

**Comment by hsanchez** [comment]
@martinschaef there are a total of 56 warnings generated by findbugs. Unfortunately, those 56 warnings are about test code generated by Randoop. **Question.** Is there a way to tell findbugs (within the gradle file) to not examine specific classes (e.g., those test classes generated by Randoop)?

**Comment by martinschaef** [comment]
I'd assume that you can exclude folders from the findbugs check. The target is defined in https://github.com/jayhorn/jayhorn/blob/devel/build.gradle#L70 ... I think this post describes how to tell findbugs to ignore stuff: http://stackoverflow.com/questions/22037499/using-excludes-config-in-findbugs-and-checkstyle-plugin-in-gradle

**Comment by hsanchez** [comment]
@martinschaef findbugs is no longer complaining. fixed the issues. Now, it is code coverage the one complaining :(. Jayhorn classes need more coverage. I will try to improve that coverage tomorrow.

**Comment by hsanchez** [comment]
@martinschaef All checks have passed!!!! Great!!

**Comment by martinschaef** [comment]
Thanks!

**Pull request merged**
